CC = gcc
CFLAGS = -ansi -Wall -g -O0 -Wwrite-strings -Wshadow -pedantic-errors -fstack-protector-all 
PROGS = fork_example1 fork_example2 fork_example3 fork_example4

all: $(PROGS)

clean: 
	rm -f a.out *.o $(PROGS)
