CC = gcc
CFLAGS= -ansi -Wall -g -O0 -Wwrite-strings -Wshadow -fstack-protector-all -pedantic-errors 
PROGS = wait_intro wait_status values_status_zero environ  

all: $(PROGS)

clean: 
	rm -f a.out *.o $(PROGS)
