CC = gcc
CFLAGS= -ansi -Wall -g -O0 -Wwrite-strings -Wshadow -fstack-protector-all -pedantic-errors 
PROGS = read_example std_in_out_fd write_example

all: $(PROGS)

clean: 
	rm -f a.out *.o $(PROGS)
