#!/bin/csh

if ($#argv != 1) then
   echo "Usage: mrm <file/directory>"
   exit(1)
endif

echo "Moving "$1" to local tmp_junk_dir"
mv $1 ~/tmp_junk_dir 
if ($? != 0) then
   echo ""
   echo "Terpito your remove script failed"
   echo ""
else
   echo ""
   echo "file/directory moved to ~/tmp_junk_dir" 
   echo ""
endif
