CC = gcc

CFLAGS= -ansi -Wall -g -O0 -Wwrite-strings -Wshadow -fstack-protector-all -pedantic-errors
PROGS = dup2_ex1 dup2_ex2 dup2_ex3 dup2_ex4

all: $(PROGS)

clean: 
	rm -f a.out *.o $(PROGS) results.txt output.txt
